[package]
name = "wbcli"
version = "0.1.0"
authors = ["Lorenzo Carbonell <lorenzo.carbonell.cerezo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
confy = "0.4.0"
serde_derive = "^1.0"
serde = "^1.0"
